services:
  main-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - main-db:/var/lib/postgresql/data
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - '9000:9000' # API порт (для кода Next.js)
      - '9001:9001' # Console порт (для браузера)
    environment:
      MINIO_ROOT_USER: minioadmin      # Логин для входа
      MINIO_ROOT_PASSWORD: minioadmin  # Пароль для входа
    volumes:
      - minio_storage:/data
    # ВАЖНО: Команда запуска сервера
    command: server /data --console-address ":9001"
volumes:
  main-db:
  minio_storage:
